title: "Communication Paper Picnic ðŸ§º"
email: "jacob.long@sc.edu"
author: "Jacob Long"
description: "A weekly basket with the latest published research in communication, political science, and friends."
baseurl: ""
url: "https://jacob-long.github.io/picnic"
github_username: "jacob-long"
exclude: 
  - "Gemfile"
  - "Gemfile.lock"
  - credentials.R